#!/bin/bash

echo "Install the service"

systemctl daemon-reload
systemctl enable eggnoggpi mpv nodm
systemctl start mpv eggnoggpi nodm
echo "@reboot    root    sleep 15; /sbin/service eggnoggpi start" >> /etc/crontab
