#!/bin/bash

echo "Install the service"

systemctl daemon-reload
systemctl enable antimicrox eggnoggpi mpv
systemctl start antimicrox mpv eggnoggpi
echo "@reboot    root    /sbin/service eggnoggpi start" >> /etc/crontab
