#!/bin/bash

echo "Install the service"

systemctl daemon-reload
systemctl enable eggnoggpi mpv
systemctl start mpv eggnoggpi
echo "@reboot    root    sleep 15; /sbin/service eggnoggpi start" >> /etc/crontab
